version: 2
jobs:
  build:
    working_directory: ~/cactus
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: ./gradlew dependencies

      - run:
          name: Test
          command: ./gradlew check

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./gradlew publish
              git push origin master --follow-tags
            fi

      - store_artifacts:
          path: test-result

      - store_test_results:
          path: test-result